//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EU4_PCP_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EU4_PCP_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU4 Province Color Picker.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.0.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Load.
        /// </summary>
        public static string AutoLoad {
            get {
                return ResourceManager.GetString("AutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Check.
        /// </summary>
        public static string CheckDupli {
            get {
                return ResourceManager.GetString("CheckDupli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Duplicates.
        /// </summary>
        public static string ColorDupli {
            get {
                return ResourceManager.GetString("ColorDupli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorPickerPageTitle {
            get {
                return ResourceManager.GetString("ColorPickerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Definition.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DisableLoad {
            get {
                return ResourceManager.GetString("DisableLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        public static string Dynamic {
            get {
                return ResourceManager.GetString("Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Last Mod.
        /// </summary>
        public static string FullyLoad {
            get {
                return ResourceManager.GetString("FullyLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path.
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Localisation.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Path.
        /// </summary>
        public static string ModPath {
            get {
                return ResourceManager.GetString("ModPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string ProvinceFiltering {
            get {
                return ResourceManager.GetString("ProvinceFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Names.
        /// </summary>
        public static string ProvinceNames {
            get {
                return ResourceManager.GetString("ProvinceNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces Table.
        /// </summary>
        public static string ProvTablePageTitle {
            get {
                return ResourceManager.GetString("ProvTablePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Table Preferences.
        /// </summary>
        public static string ProvTableSettings {
            get {
                return ResourceManager.GetString("ProvTableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game Files.
        /// </summary>
        public static string RememberLoad {
            get {
                return ResourceManager.GetString("RememberLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string SettingsButtonOffset {
            get {
                return ResourceManager.GetString("SettingsButtonOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ShellColorPickerPage {
            get {
                return ResourceManager.GetString("ShellColorPickerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string ShellProvTablePage {
            get {
                return ResourceManager.GetString("ShellProvTablePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show RNW and Unused Provinces.
        /// </summary>
        public static string ShowAllProvinces {
            get {
                return ResourceManager.GetString("ShowAllProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directories.
        /// </summary>
        public static string WorkingDirectories {
            get {
                return ResourceManager.GetString("WorkingDirectories", resourceCulture);
            }
        }
    }
}
